import { writeFile } from 'fs/promises';
import { join } from 'path';

interface ParsedPRD {
  title: string;
  overview: string;
  techStack: { category: string; technology: string }[];
  phases: {
    name: string;
    description?: string;
    tasks: { title: string; description?: string }[];
  }[];
  rawMarkdown: string;
}

/**
 * Generates a CLAUDE.md file content from a parsed PRD.
 * This file provides context for Claude Code when working on tasks.
 */
export function generateClaudeMd(prd: ParsedPRD, projectPath?: string): string {
  const techStackTable = prd.techStack.length > 0
    ? `## Tech Stack\n| Category | Technology |\n|----------|------------|\n${prd.techStack.map(t => `| ${t.category} | ${t.technology} |`).join('\n')}\n`
    : '';

  const phasesSection = prd.phases.map((phase, i) => {
    const tasksList = phase.tasks.map(t => `- [ ] ${t.title}${t.description ? ` — ${t.description}` : ''}`).join('\n');
    return `### Phase ${i + 1}: ${phase.name}\n${phase.description ? `${phase.description}\n\n` : ''}${tasksList}`;
  }).join('\n\n');

  return `# ${prd.title}

## Project Overview
${prd.overview}

${techStackTable}
## Implementation Phases

${phasesSection}

## Working with Claude Code

When Claude Code works on a task from this project:
1. Read this file first to understand the project context
2. Focus only on the specific task assigned
3. Follow the tech stack decisions outlined above
4. Keep changes minimal and focused

---
Generated by StickStack
`;
}

/**
 * Writes the CLAUDE.md file to the specified project directory.
 */
export async function writeClaudeMd(prd: ParsedPRD, projectPath: string): Promise<string> {
  const content = generateClaudeMd(prd, projectPath);
  const filePath = join(projectPath, 'CLAUDE.md');

  await writeFile(filePath, content, 'utf-8');

  return filePath;
}
